
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://ricoherlt.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-83371785-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "de"
author: "Rico Herlt"
title: "//rherlt"
description: "Rico Herlt ist CEO, Consultant, Software Architect, Xamarin und .NET Entwickler aus Berlin. Rico bloggt hauptsächlich über Softwareentwicklung."
keywords: "rico herlt rherlt C# csharp asp.net dotnet xamarin berlin software architect h3ko"
#favicon is statically referenced in _includes/head.html
#favicon: "/img/fehnsehturm-favicon.ico"

################
# Header layout #
################

black-favicon: "/img/tvtower-w.png"
greeting: "Hi, Ich bin Rico"
background-img: "../img/berlin-bg.jpeg"
me-description: "CEO, Consultant, Software Architect, Xamarin und .NET Entwickler"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Linux is only free if your time has no value."
  - text: "<strong>Algorithm</strong> <i>(noun.)</i><br>Word used by programmers when they don't want to explain what they did."
  - text: "<strong>Hardware</strong> <i>(noun.)</i><br>The part of a computer that you can <strong>kick</strong>."
  - text: "<strong>Programmer</strong> <i>(noun.)</i><br>A person who solves a problem that you didn't know you have, in a way you don't understand.<br>See also <strong>Wizard</strong>, <strong>Magician.</strong>"
  - text: "<strong>Consultant</strong> <i>(noun.)</i><br>A person who does precision guess work based on unreliable data provided by those of questionable knowlage.<br>See also <strong>Magician</strong>, <strong>Miracle Worker.</strong>"
  - text: "<strong>Project Manager</strong> <i>(noun.)</i><br>A person who thinks 9 women can deliver a baby in 1 month."
  - text: "<i>Why do Java programmers have to wear glasses?</i><br>- Because they don't C#."
  - text: "<i>How many programmers does it take to change a light bulb?</i><br>- None, that's a hardware problem."
  - text: "Real programmers count from 0."
  - text: "There is no cloud ☁.<br>- It's just someone else's computer."
  - text: "A programmer had a problem. He decided to use Java. Now he has a <strong>ProblemFactory</stong>."
  - text: "If the box says: <i>This software requires Windows XP or better.</i><br> Does that mean it will run on Linux?"
  
me-img: "https://www.gravatar.com/avatar/85f5e4fe8d9b790145e6bc8bfa7d774e?s=400"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "ricoherlt"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mail@ricoherlt.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Als Software-Consultant und -Entwickler begleitet Rico täglich Unternehmen auf dem Weg ins mobile Zeitalter. Dabei beschäftigt er sich seit fünf Jahren täglich intensiv mit der Cross-Plattform-Entwicklung unter Xamarin und Anbindung vom Apps an Web Services. Er veranstaltet leidenschaftlich gerne Programmierwettbewerbe für Studenten und organisiert in Berlin Cloud Meetups. Rico ist Microsoft Student Partner (StudentPartners.de), CEO von h3ko, Consultant, Software Architect, Xamarin und .NET Entwickler. In der Freizeit reist er gerne, am liebsten mit seinem Motorrad."
author_blurb_image: "https://www.gravatar.com/avatar/85f5e4fe8d9b790145e6bc8bfa7d774e?s=400"

##################
# Social Buttons #
##################

social:
  - title: "building"
    url: "http://www.h3ko.de"
  - title: "xing"
    url: "https://www.xing.com/profile/Rico_Herlt"
  - title: "linkedin"
    url: "https://de.linkedin.com/in/ricoherlt"
  - title: "twitter"
    url: "https://twitter.com/rherlt"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/6435375/rherlt"
  - title: "github"
    url: "https://github.com/rherlt"
  - title: "bitbucket"
    url: "https://bitbucket.org/rherlt/"
  - title: "gitlab"
    url: "https://gitlab.com/u/rherlt"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: rherlt
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Blog: 'latest-post'
  Über mich: 'about'
#  Timeline: 'timeline'
  Kontakt: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
